/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package layouts;

import components.LoginPanel;

/**
 *
 * @author vikas
 */
public class AuthLayout extends javax.swing.JPanel {

    /**
     * Creates new form AuthLayout
     */
    public AuthLayout() {
        initComponents();
        
         pnlMainPanel.add(new LoginPanel(pnlMainPanel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlNav = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        pnlImage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMainPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlNav.setBackground(new java.awt.Color(20, 104, 171));
        pnlNav.setPreferredSize(new java.awt.Dimension(900, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0);
        flowLayout1.setAlignOnBaseline(true);
        pnlNav.setLayout(flowLayout1);

        jPanel1.setBackground(new java.awt.Color(20, 104, 171));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 80));

        jLabel1.setFont(new java.awt.Font("Arima Koshi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/output-onlinepngtools.png"))); // NOI18N
        jLabel1.setText("HUSKY EVENTS");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setIconTextGap(5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pnlNav.add(jPanel1);

        pnlRoot.add(pnlNav, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setBackground(new java.awt.Color(231, 237, 239));
        pnlCenter.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlCenter.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/WhatsApp Image 2023-11-29 at 10.42.32 PM (1).jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlImage, java.awt.BorderLayout.WEST);

        pnlMainPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        pnlMainPanel.setLayout(new java.awt.BorderLayout());
        pnlCenter.add(pnlMainPanel, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        add(pnlRoot, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
